name: Deploy

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

          cache: 'gradle'

      - name: Deploy
        env:
          CATPPUCCIN_CI_BUILD: true

          PROJECT_NAME: catppuccin-kotlin

          OSSRH_USERNAME: catppuccin
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

        run: ./gradlew deploySonatype

      - name: Get Name & Version
        run: |
          echo "PROJECT_VERSION=$(cat gradle.properties | grep -Pso '(?<=projectVersion=).+')" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./build/libs

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/libs/*.jar
          generateReleaseNotes: true
          makeLatest: true
          draft: true
