name: Deploy to maven.d1s.dev (releases)

on:
  release:
    types:
      - published

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Deploy to maven.d1s.dev (releases)
        env:
          MAVEN_D1S_DEV_USERNAME: ${{ secrets.MAVEN_D1S_DEV_USERNAME }}
          MAVEN_D1S_DEV_PASSWORD: ${{ secrets.MAVEN_D1S_DEV_PASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenD1sDevRepositoryRepository

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: ./build/libs
